import Head from "next/head";
import Test from "../components/Test";

export default function Home() {
  return (
    <div className="selection:bg-myYellow selection:text-myGreen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test />
    </div>
  );
}
